# AUTOGENERATED BY ECOSCOPE-WORKFLOWS; see fingerprint in README.md for details


# ruff: noqa: E402

# %% [markdown]
# # Individual Event
# TODO: top level description

# %% [markdown]
# ## Imports

import os

from ecoscope_workflows_core.tasks.config import set_string_var as set_string_var
from ecoscope_workflows_core.tasks.config import (
    set_workflow_details as set_workflow_details,
)
from ecoscope_workflows_core.tasks.filter import (
    get_timezone_from_time_range as get_timezone_from_time_range,
)
from ecoscope_workflows_core.tasks.filter import set_time_range as set_time_range
from ecoscope_workflows_core.tasks.io import persist_text as persist_text
from ecoscope_workflows_core.tasks.io import set_er_connection as set_er_connection
from ecoscope_workflows_core.tasks.results import (
    create_map_widget_single_view as create_map_widget_single_view,
)
from ecoscope_workflows_core.tasks.results import gather_dashboard as gather_dashboard
from ecoscope_workflows_core.tasks.skip import (
    any_dependency_skipped as any_dependency_skipped,
)
from ecoscope_workflows_core.tasks.skip import any_is_empty_df as any_is_empty_df
from ecoscope_workflows_core.tasks.skip import never as never
from ecoscope_workflows_core.tasks.transformation import (
    convert_column_values_to_string as convert_column_values_to_string,
)
from ecoscope_workflows_core.tasks.transformation import (
    convert_values_to_timezone as convert_values_to_timezone,
)
from ecoscope_workflows_core.tasks.transformation import filter_df as filter_df
from ecoscope_workflows_core.tasks.transformation import map_columns as map_columns
from ecoscope_workflows_ext_apn.tasks import add_lat_lon_to_gdf as add_lat_lon_to_gdf
from ecoscope_workflows_ext_apn.tasks import ensure_dataframe as ensure_dataframe
from ecoscope_workflows_ext_apn.tasks import (
    generate_event_report as generate_event_report,
)
from ecoscope_workflows_ext_apn.tasks import get_eventnotes as get_eventnotes
from ecoscope_workflows_ext_apn.tasks import get_first_row_value as get_first_row_value
from ecoscope_workflows_ext_apn.tasks import get_user_me as get_user_me
from ecoscope_workflows_ext_custom.tasks.io import (
    download_event_attachments as download_event_attachments,
)
from ecoscope_workflows_ext_custom.tasks.io import html_to_png as html_to_png
from ecoscope_workflows_ext_custom.tasks.io import (
    process_events_details as process_events_details,
)
from ecoscope_workflows_ext_custom.tasks.io import (
    remove_file_scheme as remove_file_scheme,
)
from ecoscope_workflows_ext_custom.tasks.localization import set_locale as set_locale
from ecoscope_workflows_ext_custom.tasks.results import (
    create_scatterplot_layer as create_scatterplot_layer,
)
from ecoscope_workflows_ext_custom.tasks.results import draw_map as draw_map
from ecoscope_workflows_ext_custom.tasks.results import (
    set_base_maps_pydeck as set_base_maps_pydeck,
)
from ecoscope_workflows_ext_custom.tasks.transformation import (
    dataframe_to_dict as dataframe_to_dict,
)
from ecoscope_workflows_ext_custom.tasks.transformation import (
    get_collection_item as get_collection_item,
)
from ecoscope_workflows_ext_custom.tasks.transformation import (
    merge_two_dataframes as merge_two_dataframes,
)
from ecoscope_workflows_ext_custom.tasks.transformation import (
    select_columns as select_columns,
)
from ecoscope_workflows_ext_ecoscope.tasks.io import get_events as get_events
from ecoscope_workflows_ext_ecoscope.tasks.transformation import (
    apply_color_map as apply_color_map,
)

# %% [markdown]
# ## Set Workflow Details

# %%
# parameters

workflow_details_params = dict(
    name=...,
    description=...,
    image_url=...,
)

# %%
# call the task


workflow_details = (
    set_workflow_details.set_task_instance_id("workflow_details")
    .handle_errors()
    .with_tracing()
    .skipif(
        conditions=[
            any_is_empty_df,
            any_dependency_skipped,
        ],
        unpack_depth=1,
    )
    .partial(**workflow_details_params)
    .call()
)


# %% [markdown]
# ## Data Source

# %%
# parameters

er_client_params = dict(
    data_source=...,
)

# %%
# call the task


er_client = (
    set_er_connection.set_task_instance_id("er_client")
    .handle_errors()
    .with_tracing()
    .skipif(
        conditions=[
            any_is_empty_df,
            any_dependency_skipped,
        ],
        unpack_depth=1,
    )
    .partial(**er_client_params)
    .call()
)


# %% [markdown]
# ##

# %%
# parameters

user_details_params = dict()

# %%
# call the task


user_details = (
    get_user_me.set_task_instance_id("user_details")
    .handle_errors()
    .with_tracing()
    .skipif(
        conditions=[
            any_is_empty_df,
            any_dependency_skipped,
        ],
        unpack_depth=1,
    )
    .partial(client=er_client, **user_details_params)
    .call()
)


# %% [markdown]
# ## Define Base Maps

# %%
# parameters

base_maps_params = dict(
    base_maps=...,
)

# %%
# call the task


base_maps = (
    set_base_maps_pydeck.set_task_instance_id("base_maps")
    .handle_errors()
    .with_tracing()
    .skipif(
        conditions=[
            any_is_empty_df,
            any_dependency_skipped,
        ],
        unpack_depth=1,
    )
    .partial(**base_maps_params)
    .call()
)


# %% [markdown]
# ## Get Event Serial No.

# %%
# parameters

serial_no_params = dict(
    var=...,
)

# %%
# call the task


serial_no = (
    set_string_var.set_task_instance_id("serial_no")
    .handle_errors()
    .with_tracing()
    .skipif(
        conditions=[
            any_is_empty_df,
            any_dependency_skipped,
        ],
        unpack_depth=1,
    )
    .partial(**serial_no_params)
    .call()
)


# %% [markdown]
# ## Set Locale

# %%
# parameters

locale_params = dict()

# %%
# call the task


locale = (
    set_locale.set_task_instance_id("locale")
    .handle_errors()
    .with_tracing()
    .skipif(
        conditions=[
            any_is_empty_df,
            any_dependency_skipped,
        ],
        unpack_depth=1,
    )
    .partial(locale_str="es_ES", **locale_params)
    .call()
)


# %% [markdown]
# ## Time Range

# %%
# parameters

time_range_params = dict(
    since=...,
    until=...,
    timezone=...,
)

# %%
# call the task


time_range = (
    set_time_range.set_task_instance_id("time_range")
    .handle_errors()
    .with_tracing()
    .skipif(
        conditions=[
            any_is_empty_df,
            any_dependency_skipped,
        ],
        unpack_depth=1,
    )
    .partial(time_format="%d %b %Y %H:%M:%S", **time_range_params)
    .call()
)


# %% [markdown]
# ##

# %%
# parameters

get_timezone_params = dict()

# %%
# call the task


get_timezone = (
    get_timezone_from_time_range.set_task_instance_id("get_timezone")
    .handle_errors()
    .with_tracing()
    .skipif(
        conditions=[
            any_is_empty_df,
            any_dependency_skipped,
        ],
        unpack_depth=1,
    )
    .partial(time_range=time_range, **get_timezone_params)
    .call()
)


# %% [markdown]
# ## All Events

# %%
# parameters

events_params = dict()

# %%
# call the task


events = (
    get_events.set_task_instance_id("events")
    .handle_errors()
    .with_tracing()
    .skipif(
        conditions=[
            any_is_empty_df,
            any_dependency_skipped,
        ],
        unpack_depth=1,
    )
    .partial(
        client=er_client,
        time_range=time_range,
        event_columns=[
            "id",
            "time",
            "priority",
            "event_type",
            "location",
            "event_category",
            "reported_by",
            "serial_number",
            "geometry",
            "event_details",
        ],
        event_types=[],
        include_details=True,
        raise_on_empty=False,
        include_updates=False,
        include_display_values=True,
        include_related_events=False,
        include_null_geometry=False,
        **events_params,
    )
    .call()
)


# %% [markdown]
# ##

# %%
# parameters

convert_events_to_user_tz_params = dict()

# %%
# call the task


convert_events_to_user_tz = (
    convert_values_to_timezone.set_task_instance_id("convert_events_to_user_tz")
    .handle_errors()
    .with_tracing()
    .skipif(
        conditions=[
            any_is_empty_df,
            any_dependency_skipped,
        ],
        unpack_depth=1,
    )
    .partial(
        df=events,
        timezone=get_timezone,
        columns=["time"],
        **convert_events_to_user_tz_params,
    )
    .call()
)


# %% [markdown]
# ## Convert Serial Number to String

# %%
# parameters

convert_serial_no_params = dict()

# %%
# call the task


convert_serial_no = (
    convert_column_values_to_string.set_task_instance_id("convert_serial_no")
    .handle_errors()
    .with_tracing()
    .skipif(
        conditions=[
            any_is_empty_df,
            any_dependency_skipped,
        ],
        unpack_depth=1,
    )
    .partial(
        df=convert_events_to_user_tz,
        columns=["serial_number"],
        **convert_serial_no_params,
    )
    .call()
)


# %% [markdown]
# ## Get Event by Serial Number

# %%
# parameters

get_event_params = dict()

# %%
# call the task


get_event = (
    filter_df.set_task_instance_id("get_event")
    .handle_errors()
    .with_tracing()
    .skipif(
        conditions=[
            any_is_empty_df,
            any_dependency_skipped,
        ],
        unpack_depth=1,
    )
    .partial(
        df=convert_serial_no,
        column_name="serial_number",
        op="equal",
        value=serial_no,
        reset_index=False,
        **get_event_params,
    )
    .call()
)


# %% [markdown]
# ##

# %%
# parameters

processed_event_details_params = dict(
    map_to_titles=...,
)

# %%
# call the task


processed_event_details = (
    process_events_details.set_task_instance_id("processed_event_details")
    .handle_errors()
    .with_tracing()
    .skipif(
        conditions=[
            any_is_empty_df,
            any_dependency_skipped,
        ],
        unpack_depth=1,
    )
    .partial(
        df=get_event, client=er_client, ordered=True, **processed_event_details_params
    )
    .call()
)


# %% [markdown]
# ##

# %%
# parameters

select_event_details_params = dict()

# %%
# call the task


select_event_details = (
    select_columns.set_task_instance_id("select_event_details")
    .handle_errors()
    .with_tracing()
    .skipif(
        conditions=[
            any_is_empty_df,
            any_dependency_skipped,
        ],
        unpack_depth=1,
    )
    .partial(
        df=processed_event_details,
        raise_on_missing=False,
        columns=["event_details"],
        **select_event_details_params,
    )
    .call()
)


# %% [markdown]
# ##

# %%
# parameters

event_details_list_params = dict()

# %%
# call the task


event_details_list = (
    dataframe_to_dict.set_task_instance_id("event_details_list")
    .handle_errors()
    .with_tracing()
    .skipif(
        conditions=[
            any_is_empty_df,
            any_dependency_skipped,
        ],
        unpack_depth=1,
    )
    .partial(
        df=select_event_details,
        orient="records",
        drop_geometry=True,
        **event_details_list_params,
    )
    .call()
)


# %% [markdown]
# ##

# %%
# parameters

event_details_params = dict()

# %%
# call the task


event_details = (
    get_collection_item.set_task_instance_id("event_details")
    .handle_errors()
    .with_tracing()
    .skipif(
        conditions=[
            any_is_empty_df,
            any_dependency_skipped,
        ],
        unpack_depth=1,
    )
    .partial(
        key=[0, "event_details"],
        collection=event_details_list,
        default=None,
        raise_on_missing=True,
        **event_details_params,
    )
    .call()
)


# %% [markdown]
# ## Get Event Location

# %%
# parameters

get_event_location_params = dict()

# %%
# call the task


get_event_location = (
    get_first_row_value.set_task_instance_id("get_event_location")
    .handle_errors()
    .with_tracing()
    .skipif(
        conditions=[
            any_is_empty_df,
            any_dependency_skipped,
        ],
        unpack_depth=1,
    )
    .partial(gdf=get_event, field_name="location", **get_event_location_params)
    .call()
)


# %% [markdown]
# ## Apply Colormap to Event Type

# %%
# parameters

event_type_colormap_params = dict()

# %%
# call the task


event_type_colormap = (
    apply_color_map.set_task_instance_id("event_type_colormap")
    .handle_errors()
    .with_tracing()
    .skipif(
        conditions=[
            any_is_empty_df,
            any_dependency_skipped,
        ],
        unpack_depth=1,
    )
    .partial(
        df=get_event,
        input_column_name="event_type_display",
        output_column_name="event_type_color",
        colormap="Dark2",
        **event_type_colormap_params,
    )
    .call()
)


# %% [markdown]
# ## Create Event Scatterplot Layer

# %%
# parameters

event_scatterplot_layer_params = dict(
    data_url=...,
)

# %%
# call the task


event_scatterplot_layer = (
    create_scatterplot_layer.set_task_instance_id("event_scatterplot_layer")
    .handle_errors()
    .with_tracing()
    .skipif(
        conditions=[
            any_is_empty_df,
            any_dependency_skipped,
        ],
        unpack_depth=1,
    )
    .partial(
        geodataframe=event_type_colormap,
        layer_style={
            "auto_highlight": False,
            "opacity": 1.0,
            "get_fill_color": "event_type_color",
            "radius_min_pixels": 15,
        },
        legend={
            "label_column": "event_type_display",
            "color_column": "event_type_color",
        },
        **event_scatterplot_layer_params,
    )
    .call()
)


# %% [markdown]
# ## Draw Event Map

# %%
# parameters

event_map_params = dict(
    widget_id=...,
)

# %%
# call the task


event_map = (
    draw_map.set_task_instance_id("event_map")
    .handle_errors()
    .with_tracing()
    .skipif(
        conditions=[
            any_is_empty_df,
            any_dependency_skipped,
        ],
        unpack_depth=1,
    )
    .partial(
        geo_layers=event_scatterplot_layer,
        tile_layers=base_maps,
        static=False,
        title=None,
        max_zoom=15,
        view_state=None,
        legend_style={"placement": "bottom-right"},
        **event_map_params,
    )
    .call()
)


# %% [markdown]
# ## Persist Event Map HTML

# %%
# parameters

persist_event_map_html_params = dict(
    filename=...,
)

# %%
# call the task


persist_event_map_html = (
    persist_text.set_task_instance_id("persist_event_map_html")
    .handle_errors()
    .with_tracing()
    .skipif(
        conditions=[
            any_is_empty_df,
            any_dependency_skipped,
        ],
        unpack_depth=1,
    )
    .partial(
        root_path=os.environ["ECOSCOPE_WORKFLOWS_RESULTS"],
        filename_suffix="event_map",
        text=event_map,
        **persist_event_map_html_params,
    )
    .call()
)


# %% [markdown]
# ## Convert HTML Event Map to PNG

# %%
# parameters

event_map_to_png_params = dict()

# %%
# call the task


event_map_to_png = (
    html_to_png.set_task_instance_id("event_map_to_png")
    .handle_errors()
    .with_tracing()
    .skipif(
        conditions=[
            any_is_empty_df,
            any_dependency_skipped,
        ],
        unpack_depth=1,
    )
    .partial(
        html_path=persist_event_map_html,
        output_dir=os.environ["ECOSCOPE_WORKFLOWS_RESULTS"],
        config={"full_page": False},
        **event_map_to_png_params,
    )
    .call()
)


# %% [markdown]
# ## Create Map Widget for Event Map

# %%
# parameters

event_map_widget_params = dict(
    view=...,
)

# %%
# call the task


event_map_widget = (
    create_map_widget_single_view.set_task_instance_id("event_map_widget")
    .handle_errors()
    .with_tracing()
    .skipif(
        conditions=[
            never,
        ],
        unpack_depth=1,
    )
    .partial(
        title="Event Scatterplot Map",
        data=persist_event_map_html,
        **event_map_widget_params,
    )
    .call()
)


# %% [markdown]
# ##

# %%
# parameters

event_notes_params = dict()

# %%
# call the task


event_notes = (
    get_eventnotes.set_task_instance_id("event_notes")
    .handle_errors()
    .with_tracing()
    .skipif(
        conditions=[
            any_is_empty_df,
            any_dependency_skipped,
        ],
        unpack_depth=1,
    )
    .partial(
        event=get_event, client=er_client, use_index_as_id=False, **event_notes_params
    )
    .call()
)


# %% [markdown]
# ##

# %%
# parameters

event_subset_params = dict()

# %%
# call the task


event_subset = (
    select_columns.set_task_instance_id("event_subset")
    .handle_errors()
    .with_tracing()
    .skipif(
        conditions=[
            any_is_empty_df,
            any_dependency_skipped,
        ],
        unpack_depth=1,
    )
    .partial(
        df=get_event,
        raise_on_missing=False,
        columns=["id", "serial_number", "event_type_display"],
        **event_subset_params,
    )
    .call()
)


# %% [markdown]
# ##

# %%
# parameters

eventnotes_add_event_serial_no_params = dict()

# %%
# call the task


eventnotes_add_event_serial_no = (
    merge_two_dataframes.set_task_instance_id("eventnotes_add_event_serial_no")
    .handle_errors()
    .with_tracing()
    .skipif(
        conditions=[
            any_is_empty_df,
            any_dependency_skipped,
        ],
        unpack_depth=1,
    )
    .partial(
        left=event_notes,
        right=event_subset,
        on=None,
        how="left",
        left_on="event",
        right_on="id",
        left_index=False,
        right_index=False,
        fillna_value=None,
        **eventnotes_add_event_serial_no_params,
    )
    .call()
)


# %% [markdown]
# ##

# %%
# parameters

safe_notes_params = dict()

# %%
# call the task


safe_notes = (
    ensure_dataframe.set_task_instance_id("safe_notes")
    .handle_errors()
    .with_tracing()
    .skipif(
        conditions=[
            never,
        ],
        unpack_depth=1,
    )
    .partial(df=eventnotes_add_event_serial_no, **safe_notes_params)
    .call()
)


# %% [markdown]
# ## Add Lat/Lon to Events

# %%
# parameters

add_lat_lon_to_events_params = dict()

# %%
# call the task


add_lat_lon_to_events = (
    add_lat_lon_to_gdf.set_task_instance_id("add_lat_lon_to_events")
    .handle_errors()
    .with_tracing()
    .skipif(
        conditions=[
            any_is_empty_df,
            any_dependency_skipped,
        ],
        unpack_depth=1,
    )
    .partial(event_gdf=get_event, **add_lat_lon_to_events_params)
    .call()
)


# %% [markdown]
# ## Get Report Template Path

# %%
# parameters

get_template_path_params = dict(
    var=...,
)

# %%
# call the task


get_template_path = (
    set_string_var.set_task_instance_id("get_template_path")
    .handle_errors()
    .with_tracing()
    .skipif(
        conditions=[
            any_is_empty_df,
            any_dependency_skipped,
        ],
        unpack_depth=1,
    )
    .partial(**get_template_path_params)
    .call()
)


# %% [markdown]
# ## Download Attachments

# %%
# parameters

download_attachments_params = dict(
    attachments_subdir=...,
)

# %%
# call the task


download_attachments = (
    download_event_attachments.set_task_instance_id("download_attachments")
    .handle_errors()
    .with_tracing()
    .skipif(
        conditions=[
            any_is_empty_df,
            any_dependency_skipped,
        ],
        unpack_depth=1,
    )
    .partial(
        client=er_client,
        event_gdf=add_lat_lon_to_events,
        output_dir=os.environ["ECOSCOPE_WORKFLOWS_RESULTS"],
        use_index_as_id=False,
        skip_download=False,
        **download_attachments_params,
    )
    .call()
)


# %% [markdown]
# ## Filtered Event

# %%
# parameters

filtered_event_params = dict()

# %%
# call the task


filtered_event = (
    map_columns.set_task_instance_id("filtered_event")
    .handle_errors()
    .with_tracing()
    .skipif(
        conditions=[
            any_is_empty_df,
            any_dependency_skipped,
        ],
        unpack_depth=1,
    )
    .partial(
        df=add_lat_lon_to_events,
        drop_columns=None,
        retain_columns=[
            "id",
            "time",
            "location",
            "priority",
            "event_type",
            "serial_number",
            "event_type_display",
            "event_category",
            "reported_by",
            "lat/lon",
        ],
        rename_columns=None,
        raise_if_not_found=True,
        **filtered_event_params,
    )
    .call()
)


# %% [markdown]
# ##

# %%
# parameters

norm_template_path_params = dict()

# %%
# call the task


norm_template_path = (
    remove_file_scheme.set_task_instance_id("norm_template_path")
    .handle_errors()
    .with_tracing()
    .skipif(
        conditions=[
            any_is_empty_df,
            any_dependency_skipped,
        ],
        unpack_depth=1,
    )
    .partial(path=get_template_path, **norm_template_path_params)
    .call()
)


# %% [markdown]
# ##

# %%
# parameters

norm_output_dir_params = dict()

# %%
# call the task


norm_output_dir = (
    remove_file_scheme.set_task_instance_id("norm_output_dir")
    .handle_errors()
    .with_tracing()
    .skipif(
        conditions=[
            any_is_empty_df,
            any_dependency_skipped,
        ],
        unpack_depth=1,
    )
    .partial(path=os.environ["ECOSCOPE_WORKFLOWS_RESULTS"], **norm_output_dir_params)
    .call()
)


# %% [markdown]
# ## Generate Event Report

# %%
# parameters

generate_docx_params = dict()

# %%
# call the task


generate_docx = (
    generate_event_report.set_task_instance_id("generate_docx")
    .handle_errors()
    .with_tracing()
    .skipif(
        conditions=[
            any_is_empty_df,
            any_dependency_skipped,
        ],
        unpack_depth=1,
    )
    .partial(
        event=filtered_event,
        event_details=event_details,
        event_map_path=event_map_to_png,
        event_location=get_event_location,
        notes=safe_notes,
        user_details=user_details,
        attachments=download_attachments,
        include_attachment=True,
        template_path=norm_template_path,
        output_dir=norm_output_dir,
        **generate_docx_params,
    )
    .call()
)


# %% [markdown]
# ## Create Dashboard

# %%
# parameters

dashboard_params = dict(
    groupers=...,
    warning=...,
)

# %%
# call the task


dashboard = (
    gather_dashboard.set_task_instance_id("dashboard")
    .handle_errors()
    .with_tracing()
    .skipif(
        conditions=[
            any_is_empty_df,
            any_dependency_skipped,
        ],
        unpack_depth=1,
    )
    .partial(
        details=workflow_details,
        widgets=[event_map_widget],
        time_range=time_range,
        **dashboard_params,
    )
    .call()
)
