# AUTOGENERATED BY ECOSCOPE-WORKFLOWS; see fingerprint in README.md for details


"""WARNING: This file is generated in a testing context and should not be used in production.
Lines specific to the testing context are marked with a test tube emoji (🧪) to indicate
that they would not be included (or would be different) in the production version of this file.
"""

import os
import warnings  # 🧪
from typing import Any

from ecoscope.platform.tasks.config import set_string_var as set_string_var
from ecoscope.platform.tasks.config import set_workflow_details as set_workflow_details
from ecoscope.platform.tasks.filter import (
    get_timezone_from_time_range as get_timezone_from_time_range,
)
from ecoscope.platform.tasks.filter import set_time_range as set_time_range
from ecoscope.platform.tasks.io import set_er_connection as set_er_connection
from ecoscope.platform.tasks.results import set_base_maps as set_base_maps
from ecoscope.platform.tasks.skip import (
    any_dependency_skipped as any_dependency_skipped,
)
from ecoscope.platform.tasks.skip import any_is_empty_df as any_is_empty_df
from ecoscope_workflows_ext_apn.tasks import get_user_me as get_user_me
from ecoscope_workflows_ext_custom.tasks.localization import set_locale as set_locale
from wt_contracts import validate as _validate
from wt_task import task
from wt_task.testing import create_func_magicmock  # 🧪

from .. import metadata as _metadata

get_events = create_func_magicmock(  # 🧪
    anchor="ecoscope.platform.tasks.io",  # 🧪
    func_name="get_events",  # 🧪
)  # 🧪
from ecoscope.platform.tasks.transformation import (
    convert_column_values_to_string as convert_column_values_to_string,
)
from ecoscope.platform.tasks.transformation import (
    convert_values_to_timezone as convert_values_to_timezone,
)
from ecoscope.platform.tasks.transformation import filter_df as filter_df

process_events_details = create_func_magicmock(  # 🧪
    anchor="ecoscope.platform.tasks.io",  # 🧪
    func_name="process_events_details",  # 🧪
)  # 🧪
from ecoscope.platform.tasks.io import persist_text as persist_text
from ecoscope.platform.tasks.results import (
    create_map_widget_single_view as create_map_widget_single_view,
)
from ecoscope.platform.tasks.results import (
    create_scatterplot_layer as create_scatterplot_layer,
)
from ecoscope.platform.tasks.results import draw_map as draw_map
from ecoscope.platform.tasks.results import (
    view_state_from_layers as view_state_from_layers,
)
from ecoscope.platform.tasks.skip import never as never
from ecoscope.platform.tasks.transformation import apply_color_map as apply_color_map
from ecoscope_workflows_ext_apn.tasks import add_lat_lon_to_gdf as add_lat_lon_to_gdf
from ecoscope_workflows_ext_apn.tasks import (
    collect_optional_layers as collect_optional_layers,
)
from ecoscope_workflows_ext_apn.tasks import ensure_dataframe as ensure_dataframe
from ecoscope_workflows_ext_apn.tasks import get_eventnotes as get_eventnotes
from ecoscope_workflows_ext_apn.tasks import get_first_row_value as get_first_row_value
from ecoscope_workflows_ext_custom.tasks.io import (
    get_spatial_features as get_spatial_features,
)
from ecoscope_workflows_ext_custom.tasks.io import html_to_png as html_to_png
from ecoscope_workflows_ext_custom.tasks.io import (
    load_local_spatial_file as load_local_spatial_file,
)
from ecoscope_workflows_ext_custom.tasks.results import (
    create_spatial_features_layer as create_spatial_features_layer,
)
from ecoscope_workflows_ext_custom.tasks.transformation import (
    dataframe_to_dict as dataframe_to_dict,
)
from ecoscope_workflows_ext_custom.tasks.transformation import (
    get_collection_item as get_collection_item,
)
from ecoscope_workflows_ext_custom.tasks.transformation import (
    merge_two_dataframes as merge_two_dataframes,
)
from ecoscope_workflows_ext_custom.tasks.transformation import (
    select_columns as select_columns,
)

download_event_attachments = create_func_magicmock(  # 🧪
    anchor="ecoscope_workflows_ext_custom.tasks.io",  # 🧪
    func_name="download_event_attachments",  # 🧪
)  # 🧪
from ecoscope.platform.tasks.results import gather_dashboard as gather_dashboard
from ecoscope.platform.tasks.transformation import map_columns as map_columns
from ecoscope_workflows_ext_apn.tasks import (
    generate_event_report as generate_event_report,
)
from ecoscope_workflows_ext_custom.tasks.io import (
    remove_file_scheme as remove_file_scheme,
)


def main(params: dict[str, Any], validate_params_schema: bool = True):
    warnings.warn("This test script should not be used in production!")  # 🧪

    if validate_params_schema:
        _validate(params, _metadata.load_params_schema())

    workflow_details = (
        task(set_workflow_details)
        .validate()
        .set_task_instance_id("workflow_details")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(**(params.get("workflow_details") or {}))
        .call()
    )

    er_client = (
        task(set_er_connection)
        .validate()
        .set_task_instance_id("er_client")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(**(params.get("er_client") or {}))
        .call()
    )

    user_details = (
        task(get_user_me)
        .validate()
        .set_task_instance_id("user_details")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(client=er_client, **(params.get("user_details") or {}))
        .call()
    )

    base_maps = (
        task(set_base_maps)
        .validate()
        .set_task_instance_id("base_maps")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(**(params.get("base_maps") or {}))
        .call()
    )

    serial_no = (
        task(set_string_var)
        .validate()
        .set_task_instance_id("serial_no")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(**(params.get("serial_no") or {}))
        .call()
    )

    locale = (
        task(set_locale)
        .validate()
        .set_task_instance_id("locale")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(locale_str="es_ES", **(params.get("locale") or {}))
        .call()
    )

    time_range = (
        task(set_time_range)
        .validate()
        .set_task_instance_id("time_range")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(time_format="%d %b %Y %H:%M:%S", **(params.get("time_range") or {}))
        .call()
    )

    get_timezone = (
        task(get_timezone_from_time_range)
        .validate()
        .set_task_instance_id("get_timezone")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(time_range=time_range, **(params.get("get_timezone") or {}))
        .call()
    )

    events = (
        task(get_events)
        # 🧪 validation omitted for mocked IO task (returns pre-loaded example data)
        .set_task_instance_id("events")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            client=er_client,
            time_range=time_range,
            event_columns=[
                "id",
                "time",
                "priority_label",
                "event_type",
                "location",
                "event_category",
                "reported_by",
                "serial_number",
                "geometry",
                "event_details",
            ],
            event_types=[],
            include_details=True,
            raise_on_empty=False,
            include_updates=False,
            include_display_values=True,
            include_related_events=False,
            include_null_geometry=False,
            **(params.get("events") or {}),
        )
        .call()
    )

    convert_events_to_user_tz = (
        task(convert_values_to_timezone)
        .validate()
        .set_task_instance_id("convert_events_to_user_tz")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            df=events,
            timezone=get_timezone,
            columns=["time"],
            **(params.get("convert_events_to_user_tz") or {}),
        )
        .call()
    )

    convert_serial_no = (
        task(convert_column_values_to_string)
        .validate()
        .set_task_instance_id("convert_serial_no")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            df=convert_events_to_user_tz,
            columns=["serial_number"],
            **(params.get("convert_serial_no") or {}),
        )
        .call()
    )

    get_event = (
        task(filter_df)
        .validate()
        .set_task_instance_id("get_event")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            df=convert_serial_no,
            column_name="serial_number",
            op="equal",
            value=serial_no,
            reset_index=False,
            **(params.get("get_event") or {}),
        )
        .call()
    )

    processed_event_details = (
        task(process_events_details)
        # 🧪 validation omitted for mocked IO task (returns pre-loaded example data)
        .set_task_instance_id("processed_event_details")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            df=get_event,
            client=er_client,
            ordered=True,
            **(params.get("processed_event_details") or {}),
        )
        .call()
    )

    select_event_details = (
        task(select_columns)
        .validate()
        .set_task_instance_id("select_event_details")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            df=processed_event_details,
            raise_on_missing=False,
            columns=["event_details"],
            **(params.get("select_event_details") or {}),
        )
        .call()
    )

    event_details_list = (
        task(dataframe_to_dict)
        .validate()
        .set_task_instance_id("event_details_list")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            df=select_event_details,
            orient="records",
            drop_geometry=True,
            **(params.get("event_details_list") or {}),
        )
        .call()
    )

    event_details = (
        task(get_collection_item)
        .validate()
        .set_task_instance_id("event_details")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            key=[0, "event_details"],
            collection=event_details_list,
            default=None,
            raise_on_missing=True,
            **(params.get("event_details") or {}),
        )
        .call()
    )

    get_event_location = (
        task(get_first_row_value)
        .validate()
        .set_task_instance_id("get_event_location")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            gdf=get_event,
            field_name="location",
            **(params.get("get_event_location") or {}),
        )
        .call()
    )

    spatial_features = (
        task(get_spatial_features)
        .validate()
        .set_task_instance_id("spatial_features")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(client=er_client, **(params.get("spatial_features") or {}))
        .call()
    )

    spatial_features_layer = (
        task(create_spatial_features_layer)
        .validate()
        .set_task_instance_id("spatial_features_layer")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            geodataframe=spatial_features,
            tooltip_columns=None,
            **(params.get("spatial_features_layer") or {}),
        )
        .call()
    )

    local_spatial_file = (
        task(load_local_spatial_file)
        .validate()
        .set_task_instance_id("local_spatial_file")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(**(params.get("local_spatial_file") or {}))
        .call()
    )

    local_spatial_features_layer = (
        task(create_spatial_features_layer)
        .validate()
        .set_task_instance_id("local_spatial_features_layer")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            geodataframe=local_spatial_file,
            tooltip_columns=None,
            **(params.get("local_spatial_features_layer") or {}),
        )
        .call()
    )

    event_type_colormap = (
        task(apply_color_map)
        .validate()
        .set_task_instance_id("event_type_colormap")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            df=get_event,
            input_column_name="event_type_display",
            output_column_name="event_type_color",
            colormap="Set3",
            **(params.get("event_type_colormap") or {}),
        )
        .call()
    )

    event_scatterplot_layer = (
        task(create_scatterplot_layer)
        .validate()
        .set_task_instance_id("event_scatterplot_layer")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            geodataframe=event_type_colormap,
            layer_style={
                "auto_highlight": False,
                "opacity": 1.0,
                "get_fill_color": "event_type_color",
                "radius_min_pixels": 15,
            },
            data_url=None,
            legend={
                "label_column": "event_type_display",
                "color_column": "event_type_color",
            },
            **(params.get("event_scatterplot_layer") or {}),
        )
        .call()
    )

    optional_geo_layers = (
        task(collect_optional_layers)
        .validate()
        .set_task_instance_id("optional_geo_layers")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                never,
            ],
            unpack_depth=1,
        )
        .partial(
            layers=[
                spatial_features_layer,
                local_spatial_features_layer,
                event_scatterplot_layer,
            ],
            **(params.get("optional_geo_layers") or {}),
        )
        .call()
    )

    event_map_view_state = (
        task(view_state_from_layers)
        .validate()
        .set_task_instance_id("event_map_view_state")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            layers=[event_scatterplot_layer],
            **(params.get("event_map_view_state") or {}),
        )
        .call()
    )

    event_map = (
        task(draw_map)
        .validate()
        .set_task_instance_id("event_map")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            geo_layers=optional_geo_layers,
            tile_layers=base_maps,
            static=False,
            output_type="html",
            title=None,
            max_zoom=15,
            view_state=event_map_view_state,
            legend_style={"placement": "bottom-right"},
            **(params.get("event_map") or {}),
        )
        .call()
    )

    persist_event_map_html = (
        task(persist_text)
        .validate()
        .set_task_instance_id("persist_event_map_html")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            root_path=os.environ["ECOSCOPE_WORKFLOWS_RESULTS"],
            filename_suffix="event_map",
            text=event_map,
            **(params.get("persist_event_map_html") or {}),
        )
        .call()
    )

    event_map_to_png = (
        task(html_to_png)
        .validate()
        .set_task_instance_id("event_map_to_png")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            html_path=persist_event_map_html,
            output_dir=os.environ["ECOSCOPE_WORKFLOWS_RESULTS"],
            config={"full_page": False},
            **(params.get("event_map_to_png") or {}),
        )
        .call()
    )

    event_map_widget = (
        task(create_map_widget_single_view)
        .validate()
        .set_task_instance_id("event_map_widget")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                never,
            ],
            unpack_depth=1,
        )
        .partial(
            title="Event Scatterplot Map",
            data=persist_event_map_html,
            **(params.get("event_map_widget") or {}),
        )
        .call()
    )

    event_notes = (
        task(get_eventnotes)
        .validate()
        .set_task_instance_id("event_notes")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            event=get_event,
            client=er_client,
            use_index_as_id=False,
            **(params.get("event_notes") or {}),
        )
        .call()
    )

    event_subset = (
        task(select_columns)
        .validate()
        .set_task_instance_id("event_subset")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            df=get_event,
            raise_on_missing=False,
            columns=["id", "serial_number", "event_type_display"],
            **(params.get("event_subset") or {}),
        )
        .call()
    )

    eventnotes_add_event_serial_no = (
        task(merge_two_dataframes)
        .validate()
        .set_task_instance_id("eventnotes_add_event_serial_no")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            left=event_notes,
            right=event_subset,
            on=None,
            how="left",
            left_on="event",
            right_on="id",
            left_index=False,
            right_index=False,
            fillna_value=None,
            **(params.get("eventnotes_add_event_serial_no") or {}),
        )
        .call()
    )

    safe_notes = (
        task(ensure_dataframe)
        .validate()
        .set_task_instance_id("safe_notes")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                never,
            ],
            unpack_depth=1,
        )
        .partial(df=eventnotes_add_event_serial_no, **(params.get("safe_notes") or {}))
        .call()
    )

    add_lat_lon_to_events = (
        task(add_lat_lon_to_gdf)
        .validate()
        .set_task_instance_id("add_lat_lon_to_events")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(event_gdf=get_event, **(params.get("add_lat_lon_to_events") or {}))
        .call()
    )

    get_template_path = (
        task(set_string_var)
        .validate()
        .set_task_instance_id("get_template_path")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(**(params.get("get_template_path") or {}))
        .call()
    )

    download_attachments = (
        task(download_event_attachments)
        # 🧪 validation omitted for mocked IO task (returns pre-loaded example data)
        .set_task_instance_id("download_attachments")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            client=er_client,
            event_gdf=add_lat_lon_to_events,
            output_dir=os.environ["ECOSCOPE_WORKFLOWS_RESULTS"],
            use_index_as_id=False,
            attachments_subdir="attachments",
            **(params.get("download_attachments") or {}),
        )
        .call()
    )

    filtered_event = (
        task(map_columns)
        .validate()
        .set_task_instance_id("filtered_event")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            df=add_lat_lon_to_events,
            drop_columns=None,
            retain_columns=[
                "id",
                "time",
                "location",
                "priority_label",
                "event_type",
                "serial_number",
                "event_type_display",
                "event_category",
                "reported_by",
                "lat/lon",
            ],
            rename_columns=None,
            raise_if_not_found=True,
            duplicate_strategy="suffix",
            **(params.get("filtered_event") or {}),
        )
        .call()
    )

    norm_template_path = (
        task(remove_file_scheme)
        .validate()
        .set_task_instance_id("norm_template_path")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(path=get_template_path, **(params.get("norm_template_path") or {}))
        .call()
    )

    norm_output_dir = (
        task(remove_file_scheme)
        .validate()
        .set_task_instance_id("norm_output_dir")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            path=os.environ["ECOSCOPE_WORKFLOWS_RESULTS"],
            **(params.get("norm_output_dir") or {}),
        )
        .call()
    )

    generate_docx = (
        task(generate_event_report)
        .validate()
        .set_task_instance_id("generate_docx")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            event=filtered_event,
            event_details=event_details,
            event_map_path=event_map_to_png,
            event_location=get_event_location,
            notes=safe_notes,
            user_details=user_details,
            attachments=download_attachments,
            include_attachment=True,
            template_path=norm_template_path,
            output_dir=norm_output_dir,
            **(params.get("generate_docx") or {}),
        )
        .call()
    )

    dashboard = (
        task(gather_dashboard)
        .validate()
        .set_task_instance_id("dashboard")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            details=workflow_details,
            widgets=[event_map_widget],
            time_range=time_range,
            **(params.get("dashboard") or {}),
        )
        .call()
    )

    return dashboard
