# AUTOGENERATED BY ECOSCOPE-WORKFLOWS; see fingerprint in README.md for details

# ruff: noqa: E402

"""WARNING: This file is generated in a testing context and should not be used in production.
Lines specific to the testing context are marked with a test tube emoji (🧪) to indicate
that they would not be included (or would be different) in the production version of this file.
"""

import json
import os
import warnings  # 🧪

from ecoscope_workflows_core.graph import DependsOn, Graph, Node
from ecoscope_workflows_core.tasks.config import set_string_var as set_string_var
from ecoscope_workflows_core.tasks.config import (
    set_workflow_details as set_workflow_details,
)
from ecoscope_workflows_core.tasks.filter import (
    get_timezone_from_time_range as get_timezone_from_time_range,
)
from ecoscope_workflows_core.tasks.filter import set_time_range as set_time_range
from ecoscope_workflows_core.tasks.io import set_er_connection as set_er_connection
from ecoscope_workflows_core.tasks.skip import (
    any_dependency_skipped as any_dependency_skipped,
)
from ecoscope_workflows_core.tasks.skip import any_is_empty_df as any_is_empty_df
from ecoscope_workflows_core.testing import create_task_magicmock  # 🧪
from ecoscope_workflows_ext_apn.tasks import get_user_me as get_user_me
from ecoscope_workflows_ext_custom.tasks.localization import set_locale as set_locale
from ecoscope_workflows_ext_custom.tasks.results import (
    set_base_maps_pydeck as set_base_maps_pydeck,
)

get_events = create_task_magicmock(  # 🧪
    anchor="ecoscope_workflows_ext_ecoscope.tasks.io",  # 🧪
    func_name="get_events",  # 🧪
)  # 🧪
from ecoscope_workflows_core.tasks.transformation import (
    convert_column_values_to_string as convert_column_values_to_string,
)
from ecoscope_workflows_core.tasks.transformation import (
    convert_values_to_timezone as convert_values_to_timezone,
)
from ecoscope_workflows_core.tasks.transformation import filter_df as filter_df

process_events_details = create_task_magicmock(  # 🧪
    anchor="ecoscope_workflows_ext_custom.tasks.io",  # 🧪
    func_name="process_events_details",  # 🧪
)  # 🧪
from ecoscope_workflows_core.tasks.io import persist_text as persist_text
from ecoscope_workflows_core.tasks.results import (
    create_map_widget_single_view as create_map_widget_single_view,
)
from ecoscope_workflows_core.tasks.skip import never as never
from ecoscope_workflows_ext_apn.tasks import add_lat_lon_to_gdf as add_lat_lon_to_gdf
from ecoscope_workflows_ext_apn.tasks import ensure_dataframe as ensure_dataframe
from ecoscope_workflows_ext_apn.tasks import get_eventnotes as get_eventnotes
from ecoscope_workflows_ext_apn.tasks import get_first_row_value as get_first_row_value
from ecoscope_workflows_ext_custom.tasks.io import html_to_png as html_to_png
from ecoscope_workflows_ext_custom.tasks.results import (
    create_scatterplot_layer as create_scatterplot_layer,
)
from ecoscope_workflows_ext_custom.tasks.results import draw_map as draw_map
from ecoscope_workflows_ext_custom.tasks.transformation import (
    dataframe_to_dict as dataframe_to_dict,
)
from ecoscope_workflows_ext_custom.tasks.transformation import (
    get_collection_item as get_collection_item,
)
from ecoscope_workflows_ext_custom.tasks.transformation import (
    merge_two_dataframes as merge_two_dataframes,
)
from ecoscope_workflows_ext_custom.tasks.transformation import (
    select_columns as select_columns,
)
from ecoscope_workflows_ext_ecoscope.tasks.transformation import (
    apply_color_map as apply_color_map,
)

download_event_attachments = create_task_magicmock(  # 🧪
    anchor="ecoscope_workflows_ext_custom.tasks.io",  # 🧪
    func_name="download_event_attachments",  # 🧪
)  # 🧪
from ecoscope_workflows_core.tasks.results import gather_dashboard as gather_dashboard
from ecoscope_workflows_core.tasks.transformation import map_columns as map_columns
from ecoscope_workflows_ext_apn.tasks import (
    generate_event_report as generate_event_report,
)
from ecoscope_workflows_ext_custom.tasks.io import (
    remove_file_scheme as remove_file_scheme,
)

from ..params import Params


def main(params: Params):
    warnings.warn("This test script should not be used in production!")  # 🧪

    params_dict = json.loads(params.model_dump_json(exclude_unset=True))

    dependencies = {
        "workflow_details": [],
        "er_client": [],
        "user_details": ["er_client"],
        "base_maps": [],
        "serial_no": [],
        "locale": [],
        "time_range": [],
        "get_timezone": ["time_range"],
        "events": ["er_client", "time_range"],
        "convert_events_to_user_tz": ["events", "get_timezone"],
        "convert_serial_no": ["convert_events_to_user_tz"],
        "get_event": ["convert_serial_no", "serial_no"],
        "processed_event_details": ["get_event", "er_client"],
        "select_event_details": ["processed_event_details"],
        "event_details_list": ["select_event_details"],
        "event_details": ["event_details_list"],
        "get_event_location": ["get_event"],
        "event_type_colormap": ["get_event"],
        "event_scatterplot_layer": ["event_type_colormap"],
        "event_map": ["event_scatterplot_layer", "base_maps"],
        "persist_event_map_html": ["event_map"],
        "event_map_to_png": ["persist_event_map_html"],
        "event_map_widget": ["persist_event_map_html"],
        "event_notes": ["get_event", "er_client"],
        "event_subset": ["get_event"],
        "eventnotes_add_event_serial_no": ["event_notes", "event_subset"],
        "safe_notes": ["eventnotes_add_event_serial_no"],
        "add_lat_lon_to_events": ["get_event"],
        "get_template_path": [],
        "download_attachments": ["er_client", "add_lat_lon_to_events"],
        "filtered_event": ["add_lat_lon_to_events"],
        "norm_template_path": ["get_template_path"],
        "norm_output_dir": [],
        "generate_docx": [
            "filtered_event",
            "event_details",
            "event_map_to_png",
            "get_event_location",
            "safe_notes",
            "user_details",
            "download_attachments",
            "norm_template_path",
            "norm_output_dir",
        ],
        "dashboard": ["workflow_details", "event_map_widget", "time_range"],
    }

    nodes = {
        "workflow_details": Node(
            async_task=set_workflow_details.validate()
            .set_task_instance_id("workflow_details")
            .handle_errors()
            .with_tracing()
            .skipif(
                conditions=[
                    any_is_empty_df,
                    any_dependency_skipped,
                ],
                unpack_depth=1,
            )
            .set_executor("lithops"),
            partial=(params_dict.get("workflow_details") or {}),
            method="call",
        ),
        "er_client": Node(
            async_task=set_er_connection.validate()
            .set_task_instance_id("er_client")
            .handle_errors()
            .with_tracing()
            .skipif(
                conditions=[
                    any_is_empty_df,
                    any_dependency_skipped,
                ],
                unpack_depth=1,
            )
            .set_executor("lithops"),
            partial=(params_dict.get("er_client") or {}),
            method="call",
        ),
        "user_details": Node(
            async_task=get_user_me.validate()
            .set_task_instance_id("user_details")
            .handle_errors()
            .with_tracing()
            .skipif(
                conditions=[
                    any_is_empty_df,
                    any_dependency_skipped,
                ],
                unpack_depth=1,
            )
            .set_executor("lithops"),
            partial={
                "client": DependsOn("er_client"),
            }
            | (params_dict.get("user_details") or {}),
            method="call",
        ),
        "base_maps": Node(
            async_task=set_base_maps_pydeck.validate()
            .set_task_instance_id("base_maps")
            .handle_errors()
            .with_tracing()
            .skipif(
                conditions=[
                    any_is_empty_df,
                    any_dependency_skipped,
                ],
                unpack_depth=1,
            )
            .set_executor("lithops"),
            partial=(params_dict.get("base_maps") or {}),
            method="call",
        ),
        "serial_no": Node(
            async_task=set_string_var.validate()
            .set_task_instance_id("serial_no")
            .handle_errors()
            .with_tracing()
            .skipif(
                conditions=[
                    any_is_empty_df,
                    any_dependency_skipped,
                ],
                unpack_depth=1,
            )
            .set_executor("lithops"),
            partial=(params_dict.get("serial_no") or {}),
            method="call",
        ),
        "locale": Node(
            async_task=set_locale.validate()
            .set_task_instance_id("locale")
            .handle_errors()
            .with_tracing()
            .skipif(
                conditions=[
                    any_is_empty_df,
                    any_dependency_skipped,
                ],
                unpack_depth=1,
            )
            .set_executor("lithops"),
            partial={
                "locale_str": "es_ES",
            }
            | (params_dict.get("locale") or {}),
            method="call",
        ),
        "time_range": Node(
            async_task=set_time_range.validate()
            .set_task_instance_id("time_range")
            .handle_errors()
            .with_tracing()
            .skipif(
                conditions=[
                    any_is_empty_df,
                    any_dependency_skipped,
                ],
                unpack_depth=1,
            )
            .set_executor("lithops"),
            partial={
                "time_format": "%d %b %Y %H:%M:%S",
            }
            | (params_dict.get("time_range") or {}),
            method="call",
        ),
        "get_timezone": Node(
            async_task=get_timezone_from_time_range.validate()
            .set_task_instance_id("get_timezone")
            .handle_errors()
            .with_tracing()
            .skipif(
                conditions=[
                    any_is_empty_df,
                    any_dependency_skipped,
                ],
                unpack_depth=1,
            )
            .set_executor("lithops"),
            partial={
                "time_range": DependsOn("time_range"),
            }
            | (params_dict.get("get_timezone") or {}),
            method="call",
        ),
        "events": Node(
            async_task=get_events.validate()
            .set_task_instance_id("events")
            .handle_errors()
            .with_tracing()
            .skipif(
                conditions=[
                    any_is_empty_df,
                    any_dependency_skipped,
                ],
                unpack_depth=1,
            )
            .set_executor("lithops"),
            partial={
                "client": DependsOn("er_client"),
                "time_range": DependsOn("time_range"),
                "event_columns": [
                    "id",
                    "time",
                    "priority_label",
                    "event_type",
                    "location",
                    "event_category",
                    "reported_by",
                    "serial_number",
                    "geometry",
                    "event_details",
                ],
                "include_details": True,
                "raise_on_empty": False,
                "include_updates": False,
                "include_display_values": True,
                "include_related_events": False,
                "include_null_geometry": False,
            }
            | (params_dict.get("events") or {}),
            method="call",
        ),
        "convert_events_to_user_tz": Node(
            async_task=convert_values_to_timezone.validate()
            .set_task_instance_id("convert_events_to_user_tz")
            .handle_errors()
            .with_tracing()
            .skipif(
                conditions=[
                    any_is_empty_df,
                    any_dependency_skipped,
                ],
                unpack_depth=1,
            )
            .set_executor("lithops"),
            partial={
                "df": DependsOn("events"),
                "timezone": DependsOn("get_timezone"),
                "columns": [
                    "time",
                ],
            }
            | (params_dict.get("convert_events_to_user_tz") or {}),
            method="call",
        ),
        "convert_serial_no": Node(
            async_task=convert_column_values_to_string.validate()
            .set_task_instance_id("convert_serial_no")
            .handle_errors()
            .with_tracing()
            .skipif(
                conditions=[
                    any_is_empty_df,
                    any_dependency_skipped,
                ],
                unpack_depth=1,
            )
            .set_executor("lithops"),
            partial={
                "df": DependsOn("convert_events_to_user_tz"),
                "columns": [
                    "serial_number",
                ],
            }
            | (params_dict.get("convert_serial_no") or {}),
            method="call",
        ),
        "get_event": Node(
            async_task=filter_df.validate()
            .set_task_instance_id("get_event")
            .handle_errors()
            .with_tracing()
            .skipif(
                conditions=[
                    any_is_empty_df,
                    any_dependency_skipped,
                ],
                unpack_depth=1,
            )
            .set_executor("lithops"),
            partial={
                "df": DependsOn("convert_serial_no"),
                "column_name": "serial_number",
                "op": "equal",
                "value": DependsOn("serial_no"),
                "reset_index": False,
            }
            | (params_dict.get("get_event") or {}),
            method="call",
        ),
        "processed_event_details": Node(
            async_task=process_events_details.validate()
            .set_task_instance_id("processed_event_details")
            .handle_errors()
            .with_tracing()
            .skipif(
                conditions=[
                    any_is_empty_df,
                    any_dependency_skipped,
                ],
                unpack_depth=1,
            )
            .set_executor("lithops"),
            partial={
                "df": DependsOn("get_event"),
                "client": DependsOn("er_client"),
                "ordered": True,
            }
            | (params_dict.get("processed_event_details") or {}),
            method="call",
        ),
        "select_event_details": Node(
            async_task=select_columns.validate()
            .set_task_instance_id("select_event_details")
            .handle_errors()
            .with_tracing()
            .skipif(
                conditions=[
                    any_is_empty_df,
                    any_dependency_skipped,
                ],
                unpack_depth=1,
            )
            .set_executor("lithops"),
            partial={
                "df": DependsOn("processed_event_details"),
                "raise_on_missing": False,
                "columns": [
                    "event_details",
                ],
            }
            | (params_dict.get("select_event_details") or {}),
            method="call",
        ),
        "event_details_list": Node(
            async_task=dataframe_to_dict.validate()
            .set_task_instance_id("event_details_list")
            .handle_errors()
            .with_tracing()
            .skipif(
                conditions=[
                    any_is_empty_df,
                    any_dependency_skipped,
                ],
                unpack_depth=1,
            )
            .set_executor("lithops"),
            partial={
                "df": DependsOn("select_event_details"),
                "orient": "records",
                "drop_geometry": True,
            }
            | (params_dict.get("event_details_list") or {}),
            method="call",
        ),
        "event_details": Node(
            async_task=get_collection_item.validate()
            .set_task_instance_id("event_details")
            .handle_errors()
            .with_tracing()
            .skipif(
                conditions=[
                    any_is_empty_df,
                    any_dependency_skipped,
                ],
                unpack_depth=1,
            )
            .set_executor("lithops"),
            partial={
                "key": [
                    0,
                    "event_details",
                ],
                "collection": DependsOn("event_details_list"),
                "default": None,
                "raise_on_missing": True,
            }
            | (params_dict.get("event_details") or {}),
            method="call",
        ),
        "get_event_location": Node(
            async_task=get_first_row_value.validate()
            .set_task_instance_id("get_event_location")
            .handle_errors()
            .with_tracing()
            .skipif(
                conditions=[
                    any_is_empty_df,
                    any_dependency_skipped,
                ],
                unpack_depth=1,
            )
            .set_executor("lithops"),
            partial={
                "gdf": DependsOn("get_event"),
                "field_name": "location",
            }
            | (params_dict.get("get_event_location") or {}),
            method="call",
        ),
        "event_type_colormap": Node(
            async_task=apply_color_map.validate()
            .set_task_instance_id("event_type_colormap")
            .handle_errors()
            .with_tracing()
            .skipif(
                conditions=[
                    any_is_empty_df,
                    any_dependency_skipped,
                ],
                unpack_depth=1,
            )
            .set_executor("lithops"),
            partial={
                "df": DependsOn("get_event"),
                "input_column_name": "event_type_display",
                "output_column_name": "event_type_color",
                "colormap": "Set3",
            }
            | (params_dict.get("event_type_colormap") or {}),
            method="call",
        ),
        "event_scatterplot_layer": Node(
            async_task=create_scatterplot_layer.validate()
            .set_task_instance_id("event_scatterplot_layer")
            .handle_errors()
            .with_tracing()
            .skipif(
                conditions=[
                    any_is_empty_df,
                    any_dependency_skipped,
                ],
                unpack_depth=1,
            )
            .set_executor("lithops"),
            partial={
                "geodataframe": DependsOn("event_type_colormap"),
                "layer_style": {
                    "auto_highlight": False,
                    "opacity": 1.0,
                    "get_fill_color": "event_type_color",
                    "radius_min_pixels": 15,
                },
                "data_url": None,
                "legend": {
                    "label_column": "event_type_display",
                    "color_column": "event_type_color",
                },
            }
            | (params_dict.get("event_scatterplot_layer") or {}),
            method="call",
        ),
        "event_map": Node(
            async_task=draw_map.validate()
            .set_task_instance_id("event_map")
            .handle_errors()
            .with_tracing()
            .skipif(
                conditions=[
                    any_is_empty_df,
                    any_dependency_skipped,
                ],
                unpack_depth=1,
            )
            .set_executor("lithops"),
            partial={
                "geo_layers": DependsOn("event_scatterplot_layer"),
                "tile_layers": DependsOn("base_maps"),
                "static": False,
                "title": None,
                "max_zoom": 15,
                "view_state": None,
                "legend_style": {
                    "placement": "bottom-right",
                },
            }
            | (params_dict.get("event_map") or {}),
            method="call",
        ),
        "persist_event_map_html": Node(
            async_task=persist_text.validate()
            .set_task_instance_id("persist_event_map_html")
            .handle_errors()
            .with_tracing()
            .skipif(
                conditions=[
                    any_is_empty_df,
                    any_dependency_skipped,
                ],
                unpack_depth=1,
            )
            .set_executor("lithops"),
            partial={
                "root_path": os.environ["ECOSCOPE_WORKFLOWS_RESULTS"],
                "filename_suffix": "event_map",
                "text": DependsOn("event_map"),
            }
            | (params_dict.get("persist_event_map_html") or {}),
            method="call",
        ),
        "event_map_to_png": Node(
            async_task=html_to_png.validate()
            .set_task_instance_id("event_map_to_png")
            .handle_errors()
            .with_tracing()
            .skipif(
                conditions=[
                    any_is_empty_df,
                    any_dependency_skipped,
                ],
                unpack_depth=1,
            )
            .set_executor("lithops"),
            partial={
                "html_path": DependsOn("persist_event_map_html"),
                "output_dir": os.environ["ECOSCOPE_WORKFLOWS_RESULTS"],
                "config": {
                    "full_page": False,
                },
            }
            | (params_dict.get("event_map_to_png") or {}),
            method="call",
        ),
        "event_map_widget": Node(
            async_task=create_map_widget_single_view.validate()
            .set_task_instance_id("event_map_widget")
            .handle_errors()
            .with_tracing()
            .skipif(
                conditions=[
                    never,
                ],
                unpack_depth=1,
            )
            .set_executor("lithops"),
            partial={
                "title": "Event Scatterplot Map",
                "data": DependsOn("persist_event_map_html"),
            }
            | (params_dict.get("event_map_widget") or {}),
            method="call",
        ),
        "event_notes": Node(
            async_task=get_eventnotes.validate()
            .set_task_instance_id("event_notes")
            .handle_errors()
            .with_tracing()
            .skipif(
                conditions=[
                    any_is_empty_df,
                    any_dependency_skipped,
                ],
                unpack_depth=1,
            )
            .set_executor("lithops"),
            partial={
                "event": DependsOn("get_event"),
                "client": DependsOn("er_client"),
                "use_index_as_id": False,
            }
            | (params_dict.get("event_notes") or {}),
            method="call",
        ),
        "event_subset": Node(
            async_task=select_columns.validate()
            .set_task_instance_id("event_subset")
            .handle_errors()
            .with_tracing()
            .skipif(
                conditions=[
                    any_is_empty_df,
                    any_dependency_skipped,
                ],
                unpack_depth=1,
            )
            .set_executor("lithops"),
            partial={
                "df": DependsOn("get_event"),
                "raise_on_missing": False,
                "columns": [
                    "id",
                    "serial_number",
                    "event_type_display",
                ],
            }
            | (params_dict.get("event_subset") or {}),
            method="call",
        ),
        "eventnotes_add_event_serial_no": Node(
            async_task=merge_two_dataframes.validate()
            .set_task_instance_id("eventnotes_add_event_serial_no")
            .handle_errors()
            .with_tracing()
            .skipif(
                conditions=[
                    any_is_empty_df,
                    any_dependency_skipped,
                ],
                unpack_depth=1,
            )
            .set_executor("lithops"),
            partial={
                "left": DependsOn("event_notes"),
                "right": DependsOn("event_subset"),
                "on": None,
                "how": "left",
                "left_on": "event",
                "right_on": "id",
                "left_index": False,
                "right_index": False,
                "fillna_value": None,
            }
            | (params_dict.get("eventnotes_add_event_serial_no") or {}),
            method="call",
        ),
        "safe_notes": Node(
            async_task=ensure_dataframe.validate()
            .set_task_instance_id("safe_notes")
            .handle_errors()
            .with_tracing()
            .skipif(
                conditions=[
                    never,
                ],
                unpack_depth=1,
            )
            .set_executor("lithops"),
            partial={
                "df": DependsOn("eventnotes_add_event_serial_no"),
            }
            | (params_dict.get("safe_notes") or {}),
            method="call",
        ),
        "add_lat_lon_to_events": Node(
            async_task=add_lat_lon_to_gdf.validate()
            .set_task_instance_id("add_lat_lon_to_events")
            .handle_errors()
            .with_tracing()
            .skipif(
                conditions=[
                    any_is_empty_df,
                    any_dependency_skipped,
                ],
                unpack_depth=1,
            )
            .set_executor("lithops"),
            partial={
                "event_gdf": DependsOn("get_event"),
            }
            | (params_dict.get("add_lat_lon_to_events") or {}),
            method="call",
        ),
        "get_template_path": Node(
            async_task=set_string_var.validate()
            .set_task_instance_id("get_template_path")
            .handle_errors()
            .with_tracing()
            .skipif(
                conditions=[
                    any_is_empty_df,
                    any_dependency_skipped,
                ],
                unpack_depth=1,
            )
            .set_executor("lithops"),
            partial=(params_dict.get("get_template_path") or {}),
            method="call",
        ),
        "download_attachments": Node(
            async_task=download_event_attachments.validate()
            .set_task_instance_id("download_attachments")
            .handle_errors()
            .with_tracing()
            .skipif(
                conditions=[
                    any_is_empty_df,
                    any_dependency_skipped,
                ],
                unpack_depth=1,
            )
            .set_executor("lithops"),
            partial={
                "client": DependsOn("er_client"),
                "event_gdf": DependsOn("add_lat_lon_to_events"),
                "output_dir": os.environ["ECOSCOPE_WORKFLOWS_RESULTS"],
                "attachments_subdir": "attachments",
                "use_index_as_id": False,
            }
            | (params_dict.get("download_attachments") or {}),
            method="call",
        ),
        "filtered_event": Node(
            async_task=map_columns.validate()
            .set_task_instance_id("filtered_event")
            .handle_errors()
            .with_tracing()
            .skipif(
                conditions=[
                    any_is_empty_df,
                    any_dependency_skipped,
                ],
                unpack_depth=1,
            )
            .set_executor("lithops"),
            partial={
                "df": DependsOn("add_lat_lon_to_events"),
                "drop_columns": None,
                "retain_columns": [
                    "id",
                    "time",
                    "location",
                    "priority_label",
                    "event_type",
                    "serial_number",
                    "event_type_display",
                    "event_category",
                    "reported_by",
                    "lat/lon",
                ],
                "rename_columns": None,
                "raise_if_not_found": True,
            }
            | (params_dict.get("filtered_event") or {}),
            method="call",
        ),
        "norm_template_path": Node(
            async_task=remove_file_scheme.validate()
            .set_task_instance_id("norm_template_path")
            .handle_errors()
            .with_tracing()
            .skipif(
                conditions=[
                    any_is_empty_df,
                    any_dependency_skipped,
                ],
                unpack_depth=1,
            )
            .set_executor("lithops"),
            partial={
                "path": DependsOn("get_template_path"),
            }
            | (params_dict.get("norm_template_path") or {}),
            method="call",
        ),
        "norm_output_dir": Node(
            async_task=remove_file_scheme.validate()
            .set_task_instance_id("norm_output_dir")
            .handle_errors()
            .with_tracing()
            .skipif(
                conditions=[
                    any_is_empty_df,
                    any_dependency_skipped,
                ],
                unpack_depth=1,
            )
            .set_executor("lithops"),
            partial={
                "path": os.environ["ECOSCOPE_WORKFLOWS_RESULTS"],
            }
            | (params_dict.get("norm_output_dir") or {}),
            method="call",
        ),
        "generate_docx": Node(
            async_task=generate_event_report.validate()
            .set_task_instance_id("generate_docx")
            .handle_errors()
            .with_tracing()
            .skipif(
                conditions=[
                    any_is_empty_df,
                    any_dependency_skipped,
                ],
                unpack_depth=1,
            )
            .set_executor("lithops"),
            partial={
                "event": DependsOn("filtered_event"),
                "event_details": DependsOn("event_details"),
                "event_map_path": DependsOn("event_map_to_png"),
                "event_location": DependsOn("get_event_location"),
                "notes": DependsOn("safe_notes"),
                "user_details": DependsOn("user_details"),
                "attachments": DependsOn("download_attachments"),
                "include_attachment": True,
                "template_path": DependsOn("norm_template_path"),
                "output_dir": DependsOn("norm_output_dir"),
            }
            | (params_dict.get("generate_docx") or {}),
            method="call",
        ),
        "dashboard": Node(
            async_task=gather_dashboard.validate()
            .set_task_instance_id("dashboard")
            .handle_errors()
            .with_tracing()
            .skipif(
                conditions=[
                    any_is_empty_df,
                    any_dependency_skipped,
                ],
                unpack_depth=1,
            )
            .set_executor("lithops"),
            partial={
                "details": DependsOn("workflow_details"),
                "widgets": [
                    DependsOn("event_map_widget"),
                ],
                "time_range": DependsOn("time_range"),
            }
            | (params_dict.get("dashboard") or {}),
            method="call",
        ),
    }
    graph = Graph(dependencies=dependencies, nodes=nodes)
    results = graph.execute()
    return results
