workflow_details:
  description: ""
  name: Individual Event
er_client:
  data_source:
    name: apn
time_range:
  timezone:
    label: Africa/Nairobi
    tzCode: EAT
    name: Nairobi
    utc: +03:00
  since: "2025-12-10T07:57:00.000Z"
  until: "2025-12-18T07:58:00.000Z"
serial_no:
  var: "349"
get_template_path:
  var: "/Users/zak/Desktop/Reporte de Evento Individual.docx"
