[project]
name = "individual-event"
channels = [
    # Uncomment the following lines to use local channels for development.
    # "file:///tmp/ecoscope-workflows/release/artifacts/",
    # "file:///tmp/ecoscope-workflows-custom/release/artifacts/",
    'https://repo.prefix.dev/ecoscope-workflows/',
    'https://repo.prefix.dev/ecoscope-workflows-custom/',
    'conda-forge',
]
platforms = ['linux-64', 'osx-arm64', 'win-64']

[dependencies]
curl = "*"
rattler-build = "*"
yq = "*"
hatch = "*"

[feature.compile.dependencies]
# Include this if you add new tasks and the package has been built
# ecoscope-workflows-ext-individual-event = "*"

ecoscope-workflows-core = "0.18.0.*"
# Here we don't specify the channel on purpose, as we want to use the local channel if it exists,
# otherwise we fall back to the remote channel.
# If you want to ensure a specific channel to incorporate your local changes, you can uncomment the line below.
# ecoscope-workflows-core = { version = "*", channel = "file:///tmp/ecoscope-workflows/release/artifacts/" }
# ecoscope-workflows-ext-individual-event = { version = "*", channel = "file:///tmp/ecoscope-workflows-custom/release/artifacts/" }

[environments]
compile = { features = [
    "compile",
], solve-group = "compile", no-default-feature = true }

[tasks]
[tasks.build-release]
cmd = './publish/build.sh'

[tasks.pytest-310]
cmd = './dev/pytest-task.sh 310'

[tasks.pytest-311]
cmd = './dev/pytest-task.sh 311'

[tasks.pytest-312]
cmd = './dev/pytest-task.sh 312'

[feature.compile.tasks.compile-individual-event]
cmd = './dev/recompile.sh individual-event --install'
depends-on = ["build-release"]

[feature.compile.tasks.recompile-individual-event]
cmd = './dev/recompile.sh individual-event --update'
depends-on = ["build-release"]
